notificacion:
  webhook:
    url: https://n8nworkflows1.app.n8n.cloud/webhook-test/44e87a4a-2b6b-4f81-84ef-1c336eb39ced

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: arka
    password: arka123